CREATE DATABASE XPERT_CARD_TABLE;

USE XPERT_CARD_TABLE;

CREATE TABLA TAHURES(
	id int(11) NOT NULL,
	Nombre VARCHAR (24) NOT NULL,
	Apellido VARCHAR (24) NOT NULL,
	Mail VARCHAR (60) NOT NULL,
	Contra VARCHAR (60) NOT NULL
);

ALTER TABLE TAHURES
    ADD PRIMARY KEY (id);

ALTER TABLE TAHURES
   MODIFI id INT(11) NOT NULL AUTO_INCREMENT;

   DESCRIBE TAHURES;